[package]
name = "modulo"
version = "0.1.2"
authors = ["Wadelma <>"]
description = "Simple modulo operation."
repository = "https://github.com/WaDelma/modulo"
documentation = "https://docs.rs/modulo/"
readme = "README.md"
keywords = [ "modulo" ]
categories = [ "algorithms" ]
license = "MIT"
